# Generated by Django 3.2.16 on 2023-10-09 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('highlight', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.CharField(blank=True, max_length=256, null=True)),
                ('thumbnail', models.ImageField(upload_to='marketplace/courses/tiers/media')),
                ('mostPopular', models.BooleanField(blank=True, null=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('tier_id', models.CharField(max_length=256)),
                ('application_id', models.CharField(max_length=256)),
                ('collector_id', models.CharField(max_length=256)),
                ('external_reference', models.CharField(blank=True, max_length=256, null=True)),
                ('init_point', models.CharField(blank=True, max_length=256, null=True)),
                ('date_created', models.CharField(max_length=256)),
                ('last_modified', models.CharField(max_length=256)),
                ('reason', models.CharField(max_length=256)),
                ('frequency', models.IntegerField()),
                ('frequency_type', models.CharField(choices=[('months', 'Months')], max_length=10)),
                ('repetitions', models.IntegerField(blank=True, null=True)),
                ('billing_day', models.IntegerField()),
                ('billing_day_proportional', models.BooleanField(default=True)),
                ('free_trial_frequency', models.IntegerField(blank=True, null=True)),
                ('free_trial_frequency_type', models.CharField(blank=True, choices=[('months', 'Months')], max_length=10, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_amount_proportional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency_id', models.CharField(max_length=3)),
                ('payment_methods_allowed', models.JSONField(blank=True, default=dict, null=True)),
                ('back_url', models.URLField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], max_length=20)),
                ('features', models.ManyToManyField(to='tiers.Feature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.EmailField(max_length=256)),
                ('subscription_id', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('external_reference', models.CharField(max_length=256)),
                ('preapproval_plan_id', models.CharField(max_length=256)),
                ('init_point', models.URLField()),
                ('back_url', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=20)),
                ('payer_id', models.CharField(max_length=256)),
                ('card_id', models.CharField(max_length=256)),
                ('payment_method_id', models.CharField(max_length=256)),
                ('next_payment_date', models.CharField(max_length=256)),
                ('date_created', models.CharField(max_length=256)),
                ('last_modified', models.CharField(max_length=256)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='tiers.tier')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
