# Generated by Django 3.2.16 on 2023-10-07 18:42

import apps.courses.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('is_accepted_answer', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('token_id', models.TextField(blank=True, null=True, unique=True)),
                ('nft_address', models.CharField(blank=True, default=0, max_length=256, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('short_description', models.TextField(blank=True, max_length=169, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('discount_until', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('discount', models.BooleanField(default=False)),
                ('payment', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=100)),
                ('language', models.CharField(blank=True, choices=[('español', 'Español'), ('ingles', 'Ingles')], max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('taught', models.CharField(blank=True, max_length=120, null=True)),
                ('welcome_message', models.CharField(blank=True, max_length=1200, null=True)),
                ('congrats_message', models.CharField(blank=True, max_length=1200, null=True)),
                ('sold', models.IntegerField(blank=True, default=0)),
                ('course_length', models.CharField(blank=True, default=0, max_length=20, null=True)),
                ('students', models.IntegerField(blank=True, default=0)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('best_seller', models.BooleanField(default=False)),
                ('goals', models.BooleanField(default=False)),
                ('course_structure', models.BooleanField(default=False)),
                ('setup', models.BooleanField(default=False)),
                ('film', models.BooleanField(default=False)),
                ('curriculum', models.BooleanField(default=False)),
                ('captions', models.BooleanField(default=False)),
                ('accessibility', models.BooleanField(default=False)),
                ('landing_page', models.BooleanField(default=False)),
                ('pricing', models.BooleanField(default=False)),
                ('promotions', models.BooleanField(default=False)),
                ('allow_messages', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=True)),
                ('banned', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='category.category')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='episodes')),
                ('filename', models.CharField(blank=True, max_length=1200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
                ('length', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('free', models.BooleanField(blank=True, default=False, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('section_uuid', models.UUIDField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('published', models.BooleanField(blank=True, default=False, null=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='episode_comments', to='courses.Comment')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_belongs_to_course', to='courses.course')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liked_course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viewed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewed_course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='course_analytics_reverse', serialize=False, to='courses.course')),
                ('views', models.IntegerField(blank=True, default=0)),
                ('clicks', models.IntegerField(blank=True, default=0, null=True)),
                ('impressions', models.IntegerField(blank=True, default=0, null=True)),
                ('clickThroughRate', models.FloatField(blank=True, default=0, null=True)),
                ('purchases', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.FloatField(blank=True, default=0, null=True)),
                ('avg_time_on_page', models.FloatField(blank=True, default=0, null=True)),
                ('sold', models.IntegerField(blank=True, default=0, null=True)),
                ('income_earned', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_items', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(to='courses.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhoIsFor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whoisfor_belongs_to_course', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_whoisfor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatLearnt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatlearnt_belongs_to_course', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_whatlearnt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewedItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.viewed')),
            ],
        ),
        migrations.CreateModel(
            name='ViewedCoursesLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(blank=True, to='courses.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_viewed_courses_library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Viewed Courses',
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_view_count', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('learning_objective', models.CharField(blank=True, max_length=1200, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_belongs_to_course', to='courses.course')),
                ('episodes', models.ManyToManyField(blank=True, to='courses.Episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_section', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.courses.models.course_directory_path)),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_resource', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisite_belongs_to_course', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_requisite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_belongs_to_course', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_rate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('has_accepted_answer', models.BooleanField(default=False)),
                ('answers', models.ManyToManyField(blank=True, related_name='question_answers', to='courses.Answer')),
                ('correct_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='courses.answer')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='question_dislikes', to='courses.Like')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_belongs_to_question', to='courses.episode')),
                ('likes', models.ManyToManyField(blank=True, related_name='question_likes', to='courses.Like')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_question', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaidCoursesList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(to='courses.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_paid_courses_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('file', models.FileField(upload_to='marketplace/courses/media')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_episode_complete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='episode_questions', to='courses.Question'),
        ),
        migrations.AddField(
            model_name='episode',
            name='resources',
            field=models.ManyToManyField(blank=True, to='courses.Resource'),
        ),
        migrations.AddField(
            model_name='episode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_episode', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_disliked_course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='images',
            field=models.ManyToManyField(blank=True, limit_choices_to={'media_type': 'image'}, related_name='course_images', to='courses.Media'),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='courseRating', to='courses.Rate'),
        ),
        migrations.AddField(
            model_name='course',
            name='requisites',
            field=models.ManyToManyField(blank=True, related_name='requisite_from_course', to='courses.Requisite'),
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='resources_from_course', to='courses.Resource'),
        ),
        migrations.AddField(
            model_name='course',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='section_from_course', to='courses.Section'),
        ),
        migrations.AddField(
            model_name='course',
            name='sellers',
            field=models.ManyToManyField(blank=True, related_name='courseSellers', to='courses.Sellers'),
        ),
        migrations.AddField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_category_courses', to='category.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topic_courses', to='category.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'media_type': 'video'}, related_name='course_videos', to='courses.Media'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_learnt',
            field=models.ManyToManyField(blank=True, related_name='whatlearnt_from_course', to='courses.WhatLearnt'),
        ),
        migrations.AddField(
            model_name='course',
            name='who_is_for',
            field=models.ManyToManyField(blank=True, related_name='whoisfor_from_course', to='courses.WhoIsFor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='comment_dislikes', to='courses.Like'),
        ),
        migrations.AddField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_comments', to='courses.episode'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to='courses.Like'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='answer_dislikes', to='courses.Like'),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='answer_likes', to='courses.Like'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_question_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='analytics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_analytics', to='courses.courseanalytics'),
        ),
    ]
