# Generated by Django 3.2.16 on 2023-11-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, choices=[('español', 'Español'), ('english', 'English')], max_length=50, null=True),
        ),
    ]
